# Generated by Django 3.0.4 on 2020-04-01 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0006_magazine_magazineloan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazine',
            name='author',
        ),
    ]
