# Generated by Django 3.0.4 on 2020-04-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0007_remove_magazine_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='author',
            field=models.CharField(default='test', max_length=200),
        ),
    ]
